[project]
site_name = "NPM Mirror"
site_description = "An internal Verdaccio-based Registry for mirroring and caching npm"
site_author = "Mohammad Taha Batoomi"
repo_url = "https://github.com/cipherunits/npm-mirror"
edit_uri = "edit/main/docs/"

docs_dir = "docs"
site_dir = "site"

language = "en"

nav = [
  { "Getting Started" = "index.md" },
  { "How It Works" = "how-it-works.md" },
  { "Installation & Setup" = "getting-started.md" },
  { "Team Setup" = "team-setup.md" },
  { "Configuration" = "configuration.md" },
  { "Preloading" = "preload.md" },
  { "Backup and Restore" = "backup.md" },
  { "Project Structure" = "structure.md" },
  { "Offline Mode" = "offline.md" }
]

features = [
  "navigation.tracking",
  "navigation.path",
  "navigation.prune",
  "navigation.indexes",
  "navigation.instant",
  "navigation.top",
  "content.code.copy",
  "content.footnote.tooltips",
  "content.tooltips",
  "search.highlight"
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
scheme = "default"
toggle.icon = "lucide/sun-moon"
toggle.name = "Toggle theme"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/cipherunits/npm-mirror"